"""empty message

Revision ID: 8e7617b9146e
Revises: 26d85c149f47
Create Date: 2025-03-01 18:58:50.978653

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '8e7617b9146e'
down_revision = '26d85c149f47'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_type',
    sa.Column('type_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('typename', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('type_id')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_type_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'user_type', ['user_type_id'], ['type_id'])
        batch_op.drop_column('user_type')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_type', mysql.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('user_type_id')

    op.drop_table('user_type')
    # ### end Alembic commands ###
